version: '3.9'

services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - flat-network

  nginx:
    networks:
      flat-network:
        aliases :
          - translate.cauduro.dev
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - certbot
      - libretranslate
    networks:
      - flat-network
      
  libretranslate:
    image: libretranslate/libretranslate
    restart: always
    env:
      - LT_LOAD_ONLY=it,en,es,de,fr,pt
    ports:
      - 5000:5000
    networks:
      - flat-network

networks:
  flat-network:
    driver: bridge